
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    domain: jx.dev.303net.net
    http: true
    tlsacme: false

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

preview:
  nameOverride: go-web
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent

go-db:
  fullnameOverride: go-db
  mysqlUser: testing
  mysqlPassword: "foo-foo-foo-foo"
  mysqlRootPassword: "foo-bar-foo-bar"
  initializationFiles:
    demo-db.sql: |-
      CREATE DATABASE demo;
      CREATE TABLE demo.COUNTER (count int);
      INSERT INTO demo.COUNTER VALUES(0);
      GRANT ALL PRIVILEGES ON demo.* TO 'testing'@'%';
      FLUSH PRIVILEGES;
